### ISSUE TITLE
Analysis parameters

### ISSUE THREAD

**Issue by cveaux** [grrrr/nsgt#22]
Hi,

thanks for this repository! 
I am trying to analyse a speech sample of 3s duration and 24kHz sampling rate but I'm a bit puzzled at the choice of some parameters.

First this is the classical mel spectrogram of the signal (estimated by librosa melspectrogram):
![mel-spectrogram](https://user-images.githubusercontent.com/22403532/72682430-e2207380-3ac4-11ea-9a20-88569af7a47a.png)

and this is the result of the cqt (librosa.cqt):
![demo_12_0](https://user-images.githubusercontent.com/22403532/72682460-27dd3c00-3ac5-11ea-86bd-e5629d77dcac.png)

I'd basically like to have the same result than the cqt (I'd like to be able to separate the glottal pulses in the high frequencies) but with a mel scale and the possibility of inversion that comes with the nsgt framework. However I cannot figure out the right choice of parameters that would give me similar results as the cqt display above but on mel scale. This is the best result that I could have
<img width="994" alt="nsgt --trlen 200 --sllen 7200" src="https://user-images.githubusercontent.com/22403532/72682723-22352580-3ac8-11ea-9277-daae872190a9.png">
with the following arguments
```python spectrogram.py sample.wav --sr 24000 --fmin=80 --fmax=10000 --bins=202 --real --scale=mel --reducedform=1 --fps=100  --plot  --matrixform  --trlen 200 --sllen 7200```

It is  kind of similar of the mel-spectrogram above and does not have the fine temporal resolution that I am looking for in the high frequencies. I understand that the choice of `sllen` and `trlen` is crucial for this but what should guide the choice?  
Also I gather that `matrixform` is the parameter used to keep the same time division among frequency bins by pooling the bins in the high frequences (that have better time resolution in the nsgt)? Is it a parameter that I should disable to have a better temporal resolution in the high frequencies as in the cqt display above? 

Ps: I tried removing the option matrixform and it yields to an error anyway:
```Traceback (most recent call last):
  File "spectrogram.py", line 111, in <module>
    coefs = assemble_coeffs(c, ncoefs)
  File "spectrogram.py", line 27, in assemble_coeffs
    out = np.empty((ncoefs, cq0.shape[1], cq0.shape[2]), dtype=cq0.dtype)
IndexError: tuple index out of range```

**Comment by lostanlen** [comment]
@cveaux hello. Note that, as of librosa v0.7.0, the melspectrogram function is invertible (via fast Griffin-Lim)

**Comment by grrrr** [comment]
Hi, definitely you'll have to use the `--matrixform` option. It ensures that all frequency bands are sampled with the same temporal density which you will need for a spectrogram. I am not sure if the comparison of the librosa melspectrogram and the nsgt one is balanced. It seems that the latter has a higher frequency resolution (more bins) which results in a lower temporal resolution. The `--sllen` (slice length) option is somewhat critical since it defines the actual frequency scale, like the window length in the classical STFT. The frequencies (e.g. their support in number of frames) must have integer ratios relative to the slice length. The longer, the more accurate the mel scale can be.

**Comment by cveaux** [comment]
Hi, thanks for these precisions, indeed the parameters I picked may not have been the best ones for a straight comparison. So I understand that `sllen` defines the maximum bound for the frequency resolution, as the window length in classical STFT, what would define the maximum bound of the temporal density then? (the equivalent of hop length for STFT). 

@lostanlen 
Thanks, yes the melspectrogram and Griffin-Lim are what I am using now. However, it's not optimal in terms of time vs frequency resolution because of the fixed temporal resolution. My application is speech synthesis, and the melspectrogram is not able to resolve well the harmonics of very low pitch voices (unless you're ready to use a very large window and loose a lot of temporal resolution), so the NSGT could be a better representation. 

The big advantage of the melspectrogram with Griffin-Lim is that you don't need the phase to invert it. The NSGT is invertible but - to my knowledge - you need the phase information.  I am not sure if Griffin-Lim or Phase Gradient Heap Integration methods could be transposed to NSGT.

**Comment by grrrr** [comment]
Re: time vs. frequency: The temporal resolution is proportional to the inverse of the frequency resolution (filter bandwidth) in any time frequency representation. 
You can achieve a better resolution by oversampling, e.g. with a low hop size, but then you will have to deal with an overcomplete parameter set for inversion. 
For these cases Griffin-Lim is probably a good choice.
The implementation of the sliced NSGT is done in a way that it always stays perfectly invertible. There you can't choose a low hop size but rather specfiy a transition length (trlen) between the slices.
Please note, that changes in the magnitude-only representation of the t-f parameter space (i.e., when you process the NSGT spectrogram slices) also change the phase relationships - because of the non-equidistant frequency scale these are much harder to understand than in the STFT case.
In any case, @lostanlen is definitely more capable of describing the mathematical implications than me.

**Comment by grrrr** [comment]
Dear @cveaux, if you think your questions have been reasonably answered, please close the issue.
